### ISSUE TITLE
Remove pytools

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#139]
@rsignell-usgs `pytools` became `pyaxiom` (see [here](https://github.com/kwilcox/pytools)).  We should deprecate it and change our scripts that call `pytools`.

**Comment by rsignell-usgs** [comment]
And it looks like stuff has been renamed/moved around as well.  This notebook no longer works if I switch `pytools` to `pyaxiom` (see cell 7):
http://nbviewer.ipython.org/github/rsignell-usgs/notebook/blob/master/tower_to_netcdf.ipynb

@kwilcox, how would the imports have to change after
https://github.com/rsignell-usgs/notebook/blob/master/tower_to_netcdf.py#L50
in order to have this work with `pyaxiom`?

**Comment by kwilcox** [comment]
Above links are dead, can you repost?

**Comment by rsignell-usgs** [comment]
@kwilcox, okay, I updated the links above

**Comment by kwilcox** [comment]
Fixed in https://github.com/rsignell-usgs/notebook/pull/14

**Comment by ocefpaf** [comment]
@rsignell-usgs Can we deprecate pytools?

**Comment by rsignell-usgs** [comment]
Yes!

On Saturday, April 25, 2015, Filipe <notifications@github.com> wrote:

> @rsignell-usgs <https://github.com/rsignell-usgs> Can we deprecate
> pytools?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ioos/conda-recipes/issues/139#issuecomment-96268083>.
>


-- 
Dr. Richard P. Signell   (508) 457-2229
USGS, 384 Woods Hole Rd.
Woods Hole, MA 02543-1598
