### ISSUE TITLE
Adding source package URL's to binstar ioos channel package web pages?

### ISSUE THREAD

**Issue by emiliom** [ioos/conda-recipes#262]
Currently the package pages on the ioos binstar channel don't have a link to the original package repository -- say, github, pypi, a homepage, or whatever. This obviously is not crucial, but whenever I hear or see about a package I'm unfamiliar with via the ioos binstar channel, I'm wanting to have a simple and clean pathway to the source package/project web site, w/o having to google "python <package name>". I think this would help many users learn about these packages, as it's one less hoop to jump over.

Is it possible to tweak the conda recipes to include such url, such that it'll show up as an obvious link on the ioos channel package page? Say, in the Description section (which currently appears to be empty in all packages)? For example, I assume [tardis](https://binstar.org/ioos/tardis) is neither of these: 
- https://en.wikipedia.org/wiki/TARDIS
- http://tardis.readthedocs.org

I can offer to help populating those url's in the recipes (no more than one per recipe), if there's a simple slot for it. Thanks.

**Comment by ocefpaf** [comment]
> Currently the package page on the ioos binstar channel don't have a link to the original package repository

The problem is that conda does not read the package metadata properly when creating the page.  The URL information is in the recipe though:

https://github.com/ioos/conda-recipes/blob/master/tardis/meta.yaml#L30

We can add the page metadata manually, but I prefer to wait for Continuum to fix.

Still, that won't help you with that particular package, since it was literally born yesterday :wink: 

I will add some documentation soon.  Meanwhile, if you are curious, here is it in action:

http://nbviewer.ipython.org/github/ocefpaf/DMAC_presentation/blob/gh-pages/skill/images/get_nearest_water.ipynb

PS: The notebook uses the old `utilities` module that I am re-factoring into smaller and more useful bits.  Tardis is one of them.  We use these bits a lot in the `system-test`, hopefully these modules I am creating will avoid the copy-and-paste and the fragmentation of those functions.

**Comment by emiliom** [comment]
Ah. Thanks for the clarification. Totally agree that this information shouldn't be added on binstar manually, and we should wait for Continuum to fix the metadata reading bug.

BTW, I don't have a specific interest in tardis. I only used it as a fun example.
