### ISSUE TITLE
NCO can't find libgsl

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/conda-recipes#472]
@clynnes tried to `conda install -c ioos nco` on my suggestion and it didn't work:  `nco` couldn't find `libgsl`

**Comment by ocefpaf** [comment]
The problem is that `nco` is compiled against a `gsl` from the [docker image](https://github.com/ocefpaf/centos64_conda_obvious-ci/blob/master/Dockerfile#L28).  We need to package `gsl` for conda and ship it with `nco`.

I have a conda `gsl` package here.  I am testing it against `nco` and, if it works, I will update the recipe.

**Comment by ocefpaf** [comment]
PR #474 should fix this.

**Comment by ocefpaf** [comment]
@rsignell-usgs and @clynnes the new binaries, with `gsl`, are in the channel.  Let me know if that works for you.

**Comment by rsignell-usgs** [comment]
Yes, it worked for me.    @clynnes, would you be willing to try `conda install -c ioos nco` again and let us know if it fixed your problem?

**Comment by kwilcox** [comment]
I tested and works for me!

**Comment by ocefpaf** [comment]
Thanks @kwilcox!

PS: OSX or Linux?

**Comment by kwilcox** [comment]
Linus
