### ISSUE TITLE
Possibility to also have a pyproj 1.9.3 version available?

### ISSUE THREAD

**Issue by jorisvandenbossche** [ioos/conda-recipes#534]
To use `pyproj` on Windows (64bit) and python 3.4, I need an older version (1.9.3), as all available 1.9.4 builds are not working (both in ioos as default conda channel). See the issue I reported here: https://github.com/jswhit/pyproj/issues/17

Current workaround I use it to install `pyproj` 1.9.3 from the JimInCO channel, which works, but is still one more complexity in the instructions I have to give to install geopandas on Windows. Would it be possible to also have this version available in the ioos channel? 

BTW, for the rest the ioos channel is really a life saver if you want to install these packages on windows! Thanks for that

**Comment by ocefpaf** [comment]
Hi @jorisvandenbossche,

The IOOS channel does not package pyproj for Python 3 and Windows.  I tried an failed miserably to circumvent a known bug\*. (See https://github.com/ioos/conda-recipes/pull/480.)

The one you are getting is probably from the default channel. You can verify that by setting the **show channels** option and then using **conda list** like this:

```bash
conda config --set show_channel_urls True
conda list
```

\* The IOOS builds are automatic via AppVeyor, so it is complicated to patch `distutils/msvc9compiler.py` to fix this issue.

**Comment by jorisvandenbossche** [comment]
Ah, thanks for the explanation! (that is one of the downsides of conda, it is not always clear where something is coming from when installing from a channel)

**Comment by ocefpaf** [comment]
Indeed the `conda config --set show_channel_urls True` should be the default behavior.

I will leave this issue open.  I do plan to fix pyproj build for Win+py3k on day.

**Comment by ocefpaf** [comment]
Fixe in #539

**Comment by pelson** [comment]
> Indeed the conda config --set show_channel_urls True should be the default behavior.

How about a PR to conda/conda? https://github.com/conda/conda/pull/1771 :wink:

**Comment by saulomeirelles** [comment]
Hi guys,

I just got in the same trouble as @jorisvandenbossche but using Python 2.7 on Windows 64-bits. Installing an older version from JimInCO channel did not work for me.

That happened after updating IOOS packages. I am just wondering if there is any progress on this issue. Would you mind informing me?

BTW, Cartopy is also behaving strangely with unexpected "OverFlow Error".

Thanks!

**Comment by ocefpaf** [comment]
@saulomeirelles can you send us the results of the following commands?

```bash
conda config --set show_channel_urls True
conda list
```

**Comment by saulomeirelles** [comment]
Hi @ocefpaf,

Here we go: [outputIOOS.txt](https://github.com/ioos/conda-recipes/files/36572/outputIOOS.txt) !

Cheers,

**Comment by ocefpaf** [comment]
And here is the problem:

`pyproj                    1.9.4                    py27_1    defaults`

Your `pyproj` is coming from the default channel and not ioos.

Try `conda install -c ioos pyproj` to force install it from `ioos`. And make some noise [here](https://github.com/ContinuumIO/anaconda-issues) to help get this fixed in the default channel.

**Comment by rsignell-usgs** [comment]
@ocefpaf , so if we just tell the continuum folks to use our recipe they should be okay for their build on the defaults channel?

**Comment by ocefpaf** [comment]
Hopefully yes.  However, they might not want our solutions.

Problem 1) We build `pyproj` using the bundled `proj.4` source to avoid some incompatibilities and errors.  Continuum build `pyproj` against an independently built `proj.4`.  Continuum's strategy sounds like the right thing to do.  I would even argue that `pyproj` is broken and it should be fixed to play nice with its dependency on the `proj.4` library, but due to the low support that `pyproj` has it is best to use the bundled source.  This bundled source is tweaked to work and has the EPSG stuff.

Problem 2) We build it against the unreleased `master` version of `pyproj` to take advantage some extra commits (like the use of setuptools to build it on Windows).  Continuum's builds are broken on windows because they use the released version.  In this case the "right" solution would be to patch the released version or to pressure for a new release.

**Comment by saulomeirelles** [comment]
Hi @ocefpaf ,

It worked out!

Thanks a bunch!
