### ISSUE TITLE
Wiki instructions

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#581]
@rsignell-usgs I just went over the instructions we have for [Win64](https://github.com/ioos/conda-recipes/wiki/Setting-up-the-IOOS-Python-Environment-for-Win64) with Jen and we found out that the issues reported in the [mailing list](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/w8jewHj2T1A) happens regardless of the default Python box is checked or not.

However, things went smoothly with miniconda.  That raised the question: Why do we recommend the full anaconda in the first place?  Is there a special reason not to?

**Comment by emiliom** [comment]
FYI, this week a programmer working with me will go through the Windows conda/ioos channel setup process, following the IOOS channel instructions. We're already using the Linux/miniconda version fairly extensively on 3 Linux machines; plus 1 MacOS with Anaconda, I think.

I can imagine that a good percentage of potential IOOS channel users on Windows may already be Anaconda users and have the full-blown/default Anaconda pre-installed. It'd be great if the IOOS instructions worked well with that user scenario, w/o requiring a parallel miniconda install that could add confusion.

Have the IOOS instructions worked fine with pre-2.4 Anaconda?

**Comment by ocefpaf** [comment]
> Have the IOOS instructions worked fine with pre-2.4 Anaconda?

@rsignell-usgs can say it better, but I believe so.  Following that mailing list thread it seems that a fix is in place...  Let's hope this bug goes away!

**Comment by emiliom** [comment]
Thanks. Glad you brought this up today! This programmer (Sky Bradley; not on github yet) ran into an error with the Anaconda instructions a few minutes ago. I don't know yet if he's using Anaconda 2.4, but I've pointed him to the 2.4 bug thread to see if it's the same error. FYI, he's on Windows 8.1 / Win64.

**Comment by emiliom** [comment]
Quick question: The [Win64 wiki instructions](https://github.com/ioos/conda-recipes/wiki/Setting-up-the-IOOS-Python-Environment-for-Win64) don't say anything about adding the IOOS anaconda channel to your channel list. That seems wrong to me, unless Anaconda on Windows is pure, user-friendly magic :) Is it missing a section on "Add the IOOS anaconda channel to your channel list", which the MacOS and Linux pages do have??

**Comment by ocefpaf** [comment]
The magic is in the `environment.yml` file.

https://github.com/ioos/conda-recipes/blob/master/environment.yml#L2-L3

**Comment by emiliom** [comment]
Ah. And the magic doesn't work on Linux and MacOSX with miniconda? Otherwise, the instructions to add the IOOS channel for those two OS's seem unnecessary, or maybe should be reworded.

**Comment by ocefpaf** [comment]
> And the magic doesn't work on Linux and MacOSX with miniconda?

The magic?  Yes.  Our brains to keep it up-to-date?  No! :wink:

**Comment by emiliom** [comment]
:+1:
`conda update brain`? I know I could use that ...

**Comment by rsignell-usgs** [comment]
The `environment.yml` works with all platforms.   Miniconda works on all platforms also, but we just thought windows users might be more comfortable installing Anaconda via the graphical installer.

**Comment by ocefpaf** [comment]
> Windows users might be more comfortable installing Anaconda via the graphical installer.

Maybe we can provide both routes.  A *fast* miniconda+command line and a **longer** GUI+Anaconda.

**Comment by emiliom** [comment]
> Miniconda works on all platforms also, but we just thought windows users might be more comfortable installing Anaconda via the graphical installer. 

Agreed. Plus, some of them may already have Anaconda installed and be using it actively, by the time they discover the IOOS channel. Steering those users to miniconda would not be helpful.

> Maybe we can provide both routes. A fast miniconda+command line and a longer GUI+Anaconda.

Sounds good. It's just documentation massaging. BTW, I think the same logic and user audience applies to OSX, roughly. I don't use a Mac, but I assume the Anaconda GUI is the same as on Windows; and I assume that's richer than the Anaconda Launcher alone, which I do use.

I can help edit or proofread the installation/configuration documentation on the wiki pages.

**Comment by abirger** [comment]
@ocefpaf , @emiliom , it turned out that this Windows bug is not a bug but a feature - https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/w8jewHj2T1A . 

The `deactivate.bat` script (or corresponding part of the `activate.bat` script) contains a couple of commands that effectively remove the path to the `%Anaconda2%\Script` folder from the User Path variable every time that you activate any environment other than the default:

```
    set CONDACTIVATE_PATH=%CONDA_DEFAULT_ENV%;%CONDA_DEFAULT_ENV%\Scripts;%CONDA_DEFAULT_ENV%\Library\bin;
    call set PATH=%%PATH:%CONDACTIVATE_PATH%=%%
```
Since new Anaconda does not copy scripts into environments, it forgets about the scripts location as soon as it switches to another environment (e.g., IOOS). @rsignell-usgs described a "stop-gap procedure" in the thread above but it did not work for me. The quick and dirty solution that worked was to add a command that inserts the path to Anaconda scripts right after it has been removed:

```
    set CONDACTIVATE_PATH=%CONDA_DEFAULT_ENV%;%CONDA_DEFAULT_ENV%\Scripts;%CONDA_DEFAULT_ENV%\Library\bin;
    call set PATH=%%PATH:%CONDACTIVATE_PATH%=%%
    call set PATH=%PATH%;C:\Anaconda2;C:\Anaconda2\Scripts
```
I don't know if that fix survives conda updates but it works for now, and hopefully they will fix this "feature" in the next release.

**Comment by ocefpaf** [comment]
Thanks @abirger this thread here was born from that thread in the mailing list.  We are in doubt to which solution we should recommend.  For now I would stay with `miniconda`, but I am biased since I never used the full Anaconda distribution.

**Comment by abirger** [comment]
@ocefpaf , sorry I did not read the first message carefully and missed the link to the mailing list. Anyway, the solution that was suggested by @rsignell-usgs was about static addition of the scripts location to the PATH variable. It does not work because every time a new environment is activated, the path to the scripts will be removed from the variable. So, until the issue is fixed in general, we have to either use `miniconda` or manually patch the `activate.bat` and `deactivate.bat` files. BTW, will it make sense to add the patch to the IOOS environment creation? The location of the installed Anaconda2 is known, so it should be easy to modify the batch files to automatically add it.

**Comment by ocefpaf** [comment]
> @ocefpaf , sorry I did not read the first message carefully and missed the link to the mailing list. 

No problem.

> BTW, will it make sense to add the patch to the IOOS environment creation? 

I am against baking any "IOOS" solution (we can recommend workarounds though.).  It is a bug in the Anaconda distribution and Continuum must fix that ASAP.

I am closing this issue and amending the wiki instructions.  Feedback is welcome!

Thanks all for the discussion.

**Comment by ocefpaf** [comment]
Call for reviewers :exclamation: 

I merged the instructions for all platforms into one,

https://github.com/ioos/conda-recipes/wiki/Setting-up-the-IOOS-Python-environment

and I would like to ask for our users to review/test it.

PS: The old [OSX](https://github.com/ioos/conda-recipes/wiki/Setting-up-the-IOOS-Anaconda-Python-environment-for-MacOS64) and [Win64](https://github.com/ioos/conda-recipes/wiki/Setting-up-the-IOOS-Python-Environment-for-Win64) still exist, but are no longer explicitly linked at the home page and will eventually be removed.

**Comment by abirger** [comment]
@rsignell-usgs , @ocefpaf , do you know if [Anaconda 2.4.1](http://docs.continuum.io/anaconda/changelog?mc_cid=ffd91cc1d2&mc_eid=31017a1c61) has that Windows issue fixed? Should we upgrade?

**Comment by emiliom** [comment]
FYI, someone in my shop with Windows 8.1 (Win64, I think) was successful
with Anaconda 2.4.0 creating and swapping conda envs. We read up on the
Windows issue, but somehow we didn't run into it.

Would it help you if he told us more about his Windows set up? Or does
Anaconda 2.4.1 "fixes" that feature/bug, and no need to look back?

**Comment by rsignell-usgs** [comment]
The release notes say the "fixes" are:
added missing Windows process elevation when creating menu items
added libdynd and dynd-python, which was missing in the last release
fixed Cython on Mac OS X reporting missing libgcc_s.10.5.dylib
fixed default channels being shown correctly in “conda list” after installing using Anaconda installer

So it certainly doesn't mention fixing our issue.

**Comment by abirger** [comment]
@rsignell-usgs , I thought that they just might not mention it among fixes just because they never admitted that it was a bug but rather stressed that it was a premeditated feature.

I kind of fixed my setup, and described that patch in the Wiki. However, I would be interested in knowing other ways of doing the same. Who knows, maybe we missed something there...
