### ISSUE TITLE
MacOS build on travis-ci

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#63]
Right now travis-ci MacOS builds are disabled:

http://blog.travis-ci.com/2014-05-13-multi-os-feature-available

I think it is worth writing them and ask the be on "the waiting list."

**Comment by rsignell-usgs** [comment]
Here's the response I got back from Travis-CI:
"Thanks for getting in touch. I would love to accommodate your request, but unfortunately we are very much over capacity in our OSX cloud at the moment. We are working to bring more capacity online and I've tagged this issue accordingly so that we get back in touch once we're able. Thanks so much for your patience!"

**Comment by ChrisBarker-NOAA** [comment]
In the meantime, I'm seeing how it goes to build on my OS-X box.

Running into issues as I go....

So I may be able to provide builds, and in any case if I can get it all building on my machine, we'll be that much closer to it working on a CI if one becomes available.

**Comment by rsignell-usgs** [comment]
Awesome.  Thanks Chris!

**Comment by ocefpaf** [comment]
I am building the OSX packages in the https://github.com/pyoceans/conda-recipes-pyoceans repository, that is in sync with https://github.com/ioos/conda-recipes/, using the object-c approach.

This is a work-around util we get a travis OSX slot or find a better solution.  But I am closing this issue util then.
