### ISSUE TITLE
`gdal` seems to cause problems again

### ISSUE THREAD

**Issue by darribas** [ioos/conda-recipes#847]
The CI on my environment raised this on macOS yesterday:

https://travis-ci.org/darribas/gds16/jobs/172128265

The key error message is:

```
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/travis/build/darribas/gds16/miniconda/envs/gds/lib/python2.7/site-packages/fiona/ogrext.so, 2): Library not loaded: @rpath/libnetcdf.11.dylib
  Referenced from: /Users/travis/build/darribas/gds16/miniconda/envs/gds/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 12.0.0 or later, but libnetcdf.11.dylib provides version 11.0.0
```

For convenience, the environment info is [here](https://github.com/darribas/gds16/blob/master/content/infrastructure/install_gds_stack.yml) and the Travis file [here](https://github.com/darribas/gds16/blob/master/.travis.yml).

This was working without any problem two days ago. Any idea why it's failing now (or how to work around it anyway)?

Thank you soooo much, as usual.

**Comment by ocefpaf** [comment]
> This was working without any problem two days ago

I am preparing a complete re-build of all binaries since last Monday. I need latest `conda-build` to fix a bug that prevented `gdal` from building on Windows (see https://github.com/conda/conda-build/issues/1412). It should be completed later today. I will ping you here one it is done.

PS: Just to be on the safe side I would add defaults below `ioos` and above `conda-forge`. That increased the consistency of my envs significantly in https://github.com/ocefpaf/2016-Python-course-CBO/blob/master/environment.yml

```yaml
channels:
  - ioos
  - defaults
  - conda-forge
```

**Comment by darribas** [comment]
@ocefpaf THANK you very much. Yes, please ping me when ready as I need to let students know they can download it again.

**Comment by ocefpaf** [comment]
BTW Linux and Windows are already OK. OS X is always more complicated...

**Comment by darribas** [comment]
YEs! Linux and Windows passing CI without any problem on my testing!

**Comment by ocefpaf** [comment]
All green! Including `OS X`. Let me know if that is working on your end.

**Comment by darribas** [comment]
Yahoo!!! Thanks so much @ocefpaf. Yep, CI is happy and green:

[![Build Status](https://travis-ci.org/darribas/gds_env.svg?branch=master)](https://travis-ci.org/darribas/gds_env)
