### ISSUE TITLE
Test env on Windows

### ISSUE THREAD

**Issue by ocefpaf** [ioos/conda-recipes#848]
@mwengren I finally finished the builds with `conda-build 2` here. It should fix your Windows issues with `gdal`. Please let me know.

Fixing this took 4-days, the largest commit I ever made (https://github.com/ioos/conda-recipes/commit/45f45f76a43b731cb98dd347d9cd451fa0fc73c2), an elusive bug with `conda-build` (https://github.com/conda/conda-build/issues/1412), two more bugs found (https://github.com/conda/conda-build/issues/1491 and https://github.com/conda/conda-build/issues/1494), and a lost battle in conda-forge (https://github.com/conda-forge/hdf5-feedstock/issues/41 :unamused:). I guess I need some vacation time after this one :smile: 

Let me know if that fixes your problems with https://github.com/mwengren/ioos-ws/blob/micah/SensorMLparsing_IOOSSOS.ipynb (hopefully without creating new ones :grimacing:). You should re-create the env following the instructions in https://github.com/ioos/notebooks_demos/wiki/Installing-Conda-Python-with-the-IOOS-environment

Big thanks to @msarahan! Without him on `conda-build` this would not be possible.

**Comment by mwengren** [comment]
@ocefpaf thanks!  Will a simple update ```conda update --yes --all``` solve the package issues, or do I need to recreate the whole environment?  I will try the update first anyway...

**Comment by ocefpaf** [comment]
I never tried but it seems that there is a command to update an env following the instructions of the env file:

```shell
conda env update environment.yml
```

Otherwise the channel preference might get messed up by the `.condarc`.

**Comment by mwengren** [comment]
```conda env update``` didn't work, recommend not trying it.  There seem to be some permission issues on my machine, maybe due to only being able to install Miniconda in my AppData directory (can't install globally due to permissions).  It's hard to tell the full impact, but env update command resulted in many errors/failures and mostly wiped out my IOOS env (missing libraries, etc).  So I started over from scratch with the IOOS env.  

Even after wiping out my former IOOS env completely though, it seems that the new environment is installed with the defaults channel gdal package:

```
conda list | grep gdal
gdal                      2.1.0                    py27_0
libgdal                   2.1.0                     vc9_0  [vc9]
```
Trying to force gdal from conda-forge doesn't work either:
```conda install -c conda-forge gdal```

I also have been getting this error pretty often, mostly after running conda install (in this case I ran ```conda install python=2.7``` to downgrade to Python 2.7 in this new IOOS environment)  and the error happened at the end of the package update process. .  Does this error seem significant:

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\Miniconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda\cli\main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda\plan.py", line 602, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda\instructions.py", line 86, in SYMLINK_CONDA_CMD
    symlink_conda(state['prefix'], arg)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda\install.py", line 596, in symlink_conda
    symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda\install.py", line 613, in symlink_conda_hlp
    symlink_fn(root_file, prefix_file)
  File "C:\Users\Micah.Wengren\AppData\Local\Continuum\Miniconda2\lib\site-packages\conda\install.py", line 159, in win_conda_bat_redirect
    with open(dst, "w") as f:
IOError: [Errno 13] Permission denied: 'C:\\Users\\Micah.Wengren\\AppData\\Local\\Continuum\\Miniconda2\\envs\\IOOS\\Scripts\\conda'
(IOOS)
```

The only effect I can see is that after running certain conda update commands, I have to deactivate and reactivate the environment in order to restore the 'conda' command.   Not a big deal if that's the only consequence.  I haven't noticed any others.

Sorry forcing you to witness my struggles through learning the inns and outs of conda (conda on Windows, in particular...)

**Comment by ocefpaf** [comment]
@mwengren thanks for the report. I am still re-building Python 3.4 packages (AppVeyor is quite slow) and that explains why you got `defaults` `gdal`. I assumed you changed the env file to Python 2.7 as you mentioned before.

Downgrading/updating seems quite broken in conda. I will try to get some of the information you gave me back upstream as bug reports.

You can either try to change to Python 2.7 in the env file or try Python 3.4 again (the builds just finished: https://ci.appveyor.com/project/comtbot/conda-recipes).

I tested with Python 2.7 and things worked. I am testing Python 3.4 now...

**Comment by mwengren** [comment]
I recreated the environment from envrionment.yml as is, then did the python downgrade manually ( I guess mostly because this is what I did the first time, and it was in my notes).  I can edit the file and wipe/re-create the env again, but I'd like to understand why I can't force it to install the 'gdal' from the conda-forge channel manually at this point.  

I now have Python 2.7 in my IOOS env via the downgrade, but I think there may be a dependency conflict happening that's preventing the gdal from conda-forge from being installed.  I tried both via the jupyter notebook UI (uninstalled gdal from IOOS, then reinstalled selecting the conda-forge gdal package - ver. 2.1.2), but I ended up getting only the original 2.1.0 py27_0 version from default channel.  

If I try to force the version from the command line I get a dependency conflict (maybe python 2.7 related?):
```
conda install gdal=2.1.2
Fetching package metadata ...........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - gdal 2.1.2*
  - qt -> jpeg 8*|8d
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by ocefpaf** [comment]
> but I'd like to understand why I can't force it to install the 'gdal' from the conda-forge channel manually at this point.

`gdal` is a beast that has many dependencies. All the dependencies need to be built in a consistent way, with the same pinnings and build tools. Right now `conda-forge` version of `gdal` has two issue:

- it is not build with conda-build too and, because of that, won't install on Windows since it dependents on HDF5 (see https://github.com/conda-forge/hdf5-feedstock/issues/41);
- it is compiled against `jpeg 9*` while `defaults` uses `jpeg 8*` making it hard to install together with `Qt` or anything that depends on `jpeg` but is absent in conda-forge (see https://github.com/conda-forge/gdal-feedstock/issues/112). Note that the same happens with `icu` and other decencies. It is hard to track them all down.


> I now have Python 2.7 in my IOOS env via the downgrade, but I think there may be a dependency conflict happening that's preventing the gdal from conda-forge from being installed.

Did you recreate the env? It should pull `gdal` from IOOS and that is a version that fixes all of the above. Actually all the packages here are place holders until conda-forge starts using `conda-build 2` and has a build of `Qt`.

I tested locally Python 2.7 (by changing the env file) and Python 3.4 (leaving the env file as-is). Now I am testing Python 3.5. The first two worked. The last one I will know in a few hours.

**Comment by ocefpaf** [comment]
This should be safe to close and everything is compiled with conda-build 2 in the conda-forge channel.

**Comment by rsignell-usgs** [comment]
@ocefpaf, I helped a windows user install netcdf4  the other day but forgot about ICU and pinning libnetcdf.   But everything *seemed* to go okay accessing OPeNDAP.    Will they run into problems?

**Comment by ocefpaf** [comment]
Probably not as the latest version is now patched and everything should work.

**Comment by rsignell-usgs** [comment]
awesome
