### ISSUE TITLE
MySQL-python doesn't build on OS-X

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [ioos/conda-recipes#99]
Trying to build all the recipes on OS-X

MySQL-pyton fails with:

``sh: mysql_config: command not found
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    metadata, options = get_config()
  File "/Users/chris.barker/anaconda/conda-bld/work/MySQL-python-1.2.5/setup_posix.py", line 43, in get_config
    libs = mysql_config("libs_r")
  File "/Users/chris.barker/anaconda/conda-bld/work/MySQL-python-1.2.5/setup_posix.py", line 25, in mysql_config
    raise EnvironmentError("%s not found" % (mysql_config.path,))
EnvironmentError: mysql_config not found
Command failed: /bin/bash -x -e /Users/chris.barker/PythonStuff/IOOS_packages/conda-recipes/mysql-python/build.sh``

Which makes lots of sense: MySQL python requires MySQL -- and it's not listed as a dependency on the recipe, nor is there a recipe for it in the repo.

MySQL is a notorious pain, though -- so not sure where to go from here...

-Chris

**Comment by ocefpaf** [comment]
`mysql-python` is not a dependency to any other package and it is not listed in [ioos_req_windows64.txt](https://github.com/ioos/conda-recipes/blob/master/00_env_requirements/ioos/ioos_req_windows64.txt) nor [ioos_req.txt](https://github.com/ioos/conda-recipes/blob/master/00_env_requirements/ioos/ioos_req.txt).

Maybe you can just delete that directory and let obvious-ci build the rest.  We'll leave this issue open to revisit it at a later time.

PS: `mysql_config` is present in package `libmysqlclient` (dev).  Since Linux builds work fine I guess that travis-ci must have that installed by default.

**Comment by ChrisBarker-NOAA** [comment]
Is libmysqlclient a Linux system package ? It looks like there are various binary installers for MySQL for OS-X -- maybe we could have conda use one of those somehow. But I haven't found a simple source configure && make && make install distribution anywhere...

**Comment by ocefpaf** [comment]
> Is libmysqlclient a Linux system package?

Not on my distro.  But travis does seems to have it, otherwise the build would fail for Linux.  I will investigate this further and get back to you.

> maybe we could have conda use one of those somehow.

There are two paths here:
- install it on your machine so conda can build `mysql-python`.  I do not like this, all `mysql-python` ofr OSX on conda seems to be like that.  I am not a `mysql-python`, but I guess that these packages will fail if the user does not install the same binary for MySQL as you used to build.

- Create a conda package for MySQL.  However, like you said: "MySQL is a notorious pain, though -- so not sure where to go from here..."

So here is my suggestion:  Leave `mysql-python`, it is not in our requirements list nor it is a dependency for other packages.  And unless @rsignell-usgs tells me that it is an essential package, my suggestion is to remove it from the repository entirely.

**Comment by ChrisBarker-NOAA** [comment]
Yup -- if it's not needed, leave it out.

**Comment by ocefpaf** [comment]
MySQL-python was deprecated in #120.
